name: weather_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0

  # Networking & utilities
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  geolocator: ^10.1.0
  provider: ^6.1.1
  logger: ^2.6.0
  web: ^1.1.1
  

  # Storage & auth
  flutter_secure_storage: ^9.0.0
  bcrypt: ^1.1.3


  # JSON + Freezed
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  location: ^8.0.1
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  js: ^0.6.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.0
  freezed: ^2.3.0
  json_serializable: ^6.6.1



flutter:
  uses-material-design: true

  assets:

      - lib/config/.env.dev
      - lib/config/.env.prod
      - lib/config/.env.prev
      - lib/config/.env.test


      - assets/mobile/
      - assets/desktop/
      - assets/icons/

